<?php
/**
 * Title: Sponsors Testimonials Carousel
 * Slug: giftflow/sponsors-testimonials-carousel
 * Description: Modern carousel displaying sponsor and donor testimonials, complete with organization details, impact badges, and stats—perfect for building trust and showcasing your supporters.
 * Categories: giftflow, giftflow-campaigns
 * Keywords: sponsors, testimonials
 * Viewport Width: 1280
 * Block Types: core/template-part/header
 * Inserter: yes
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--30)"><!-- wp:giftflow/sponsors-testimonials-carousel {"heading":"Real Impact, Real Stories","subheading":"See how nonprofits and corporations are transforming their giving programs with GiftFlow's transparent donation platform.","testimonials":[{"_id":"1781239390213","sponsorName":"TechCorp","color":"#6366f1","sponsorImage":null,"impactBadge":"+65% giving","quote":"GiftFlow transformed how we manage our corporate giving program. The real-time tracking and employee matching features have dramatically increased participation across all departments.","metrics":[{"_id":"1781239390214","value":"$380K","label":"Anual"},{"_id":"1781239734889","value":"2,400","label":"Donors"},{"_id":"1781239734890","value":"45","label":"Campaigns"}],"authorName":"Jane Dawson","authorRole":"VP of Corporate Social Responsibility","authorImage":null,"stars":5},{"_id":"1781239734893","sponsorName":"GreenFund","color":"#25bd27","sponsorImage":null,"impactBadge":"+42% donors","quote":"The campaign tracking and donor communication tools help us show exactly where contributions go. We've rebuilt donor trust and seen a surge in recurring monthly supporters.","metrics":[{"_id":"1781239390214","value":"$156K","label":"Quarterly"},{"_id":"1781239734889","value":"60","label":"Monthly"},{"_id":"1781239734890","value":"12","label":"Projects"}],"authorName":"Michael Santos","authorRole":"Executive Director","authorImage":null,"stars":5},{"_id":"1781239734892","sponsorName":"HopeAlliance","color":"#60559b","sponsorImage":null,"impactBadge":"+78% recurring","quote":"We've seen incredible growth in recurring donations since switching to GiftFlow. The volunteer coordination and event management tools have become essential to our operations.","metrics":[{"_id":"1781239390214","value":"$380K","label":"Anual"},{"_id":"1781239734889","value":"68","label":"Volunteers"},{"_id":"1781239734890","value":"28","label":"Events"}],"authorName":"Amanda Liu","authorRole":"Founder \u0026 CEO","authorImage":null,"stars":5},{"_id":"1781239734891","sponsorName":"MedCare","color":"#eb4b71","sponsorImage":null,"impactBadge":"+65% giving","quote":"Managing campaigns across multiple regions is now effortless. The reporting dashboard and compliance features give our board real-time insights into every dollar raised and spent.","metrics":[{"_id":"1781239390214","value":"$520K","label":"Raised"},{"_id":"1781239734889","value":"5","label":"Regions"},{"_id":"1781239734890","value":"100%","label":"Compliant"}],"authorName":"David Wilson","authorRole":"Chief Financial Officer","authorImage":null,"stars":5}],"autoplay":false,"align":"wide"} /--></div>
<!-- /wp:group -->