<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

return array(
	array(
		'code'      => 'AFN',
		'countries' => array( 'Afghanistan' ),
		'name'      => 'Afghanistan Afghani',
		'symbol'    => '&#1547;',
	),
	array(
		'code'      => 'ARS',
		'countries' => array( 'Argentina' ),
		'name'      => 'Argentine Peso',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'AWG',
		'countries' => array( 'Aruba' ),
		'name'      => 'Aruban florin',
		'symbol'    => '&#402;',
	),
	array(
		'code'      => 'AUD',
		'countries' => array( 'Australia' ),
		'name'      => 'Australian Dollar',
		'symbol'    => '&#65;&#36;',
	),
	array(
		'code'      => 'AZN',
		'countries' => array( 'Azerbaijan' ),
		'name'      => 'Azerbaijani Manat',
		'symbol'    => '&#8380;',
	),
	array(
		'code'      => 'BSD',
		'countries' => array( 'The Bahamas' ),
		'name'      => 'Bahamas Dollar',
		'symbol'    => '&#66;&#36;',
	),
	array(
		'code'      => 'BBD',
		'countries' => array( 'Barbados' ),
		'name'      => 'Barbados Dollar',
		'symbol'    => '&#66;&#100;&#115;&#36;',
	),
	array(
		'code'      => 'BDT',
		'countries' => array( 'People\'s Republic of Bangladesh' ),
		'name'      => 'Bangladeshi taka',
		'symbol'    => '&#2547;',
	),
	array(
		'code'      => 'BYN',
		'countries' => array( 'Belarus' ),
		'name'      => 'Belarus Ruble',
		'symbol'    => '&#66;&#114;',
	),
	array(
		'code'      => 'BZD',
		'countries' => array( 'Belize' ),
		'name'      => 'Belize Dollar',
		'symbol'    => '&#66;&#90;&#36;',
	),
	array(
		'code'      => 'BMD',
		'countries' => array( 'British Overseas Territory of Bermuda' ),
		'name'      => 'Bermudian Dollar',
		'symbol'    => '&#66;&#68;&#36;',
	),
	array(
		'code'      => 'BOP',
		'countries' => array( 'Bolivia' ),
		'name'      => 'Boliviano',
		'symbol'    => '&#66;&#115;',
	),
	array(
		'code'      => 'BAM',
		'countries' => array( 'Bosnia', 'Herzegovina' ),
		'name'      => 'Bosnia-Herzegovina Convertible Marka',
		'symbol'    => '&#75;&#77;',
	),
	array(
		'code'      => 'BWP',
		'countries' => array( 'Botswana' ),
		'name'      => 'Botswana pula',
		'symbol'    => '&#80;',
	),
	array(
		'code'      => 'BGN',
		'countries' => array( 'Bulgaria' ),
		'name'      => 'Bulgarian lev',
		'symbol'    => '&#1083;&#1074;',
	),
	array(
		'code'      => 'BRL',
		'countries' => array( 'Brazil' ),
		'name'      => 'Brazilian real',
		'symbol'    => '&#82;&#36;',
	),
	array(
		'code'      => 'BND',
		'countries' => array( 'Sultanate of Brunei' ),
		'name'      => 'Brunei dollar',
		'symbol'    => '&#66;&#36;',
	),
	array(
		'code'      => 'KHR',
		'countries' => array( 'Cambodia' ),
		'name'      => 'Cambodian riel',
		'symbol'    => '&#6107;',
	),
	array(
		'code'      => 'CAD',
		'countries' => array( 'Canada' ),
		'name'      => 'Canadian dollar',
		'symbol'    => '&#67;&#36;',
	),
	array(
		'code'      => 'KYD',
		'countries' => array( 'Cayman Islands' ),
		'name'      => 'Cayman Islands dollar',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'CLP',
		'countries' => array( 'Chile' ),
		'name'      => 'Chilean peso',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'CNY',
		'countries' => array( 'China' ),
		'name'      => 'Chinese Yuan Renminbi',
		'symbol'    => '&#165;',
	),
	array(
		'code'      => 'COP',
		'countries' => array( 'Colombia' ),
		'name'      => 'Colombian peso',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'CRC',
		'countries' => array( 'Costa Rica' ),
		'name'      => 'Costa Rican colón',
		'symbol'    => '&#8353;',
	),
	array(
		'code'      => 'HRK',
		'countries' => array( 'Croatia' ),
		'name'      => 'Croatian kuna',
		'symbol'    => '&#107;&#110;',
	),
	array(
		'code'      => 'CUP',
		'countries' => array( 'Cuba' ),
		'name'      => 'Cuban peso',
		'symbol'    => '&#8369;',
	),
	array(
		'code'      => 'CZK',
		'countries' => array( 'Czech Republic' ),
		'name'      => 'Czech koruna',
		'symbol'    => '&#75;&#269;',
	),
	array(
		'code'      => 'DKK',
		'countries' => array( 'Denmark', 'Greenland', 'The Faroe Islands' ),
		'name'      => 'Danish krone',
		'symbol'    => '&#107;&#114;',
	),
	array(
		'code'      => 'DOP',
		'countries' => array( 'Dominican Republic' ),
		'name'      => 'Dominican peso',
		'symbol'    => '&#82;&#68;&#36;',
	),
	array(
		'code'      => 'XCD',
		'countries' => array( 'Antigua and Barbuda', 'Commonwealth of Dominica', 'Grenada', 'Montserrat', 'St. Kitts and Nevis', 'Saint Lucia and St. Vincent', 'The Grenadines' ),
		'name'      => 'Eastern Caribbean dollar',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'EGP',
		'countries' => array( 'Egypt' ),
		'name'      => 'Egyptian pound',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'SVC',
		'countries' => array( 'El Salvador' ),
		'name'      => 'Salvadoran colón',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'EEK',
		'countries' => array( 'Estonia' ),
		'name'      => 'Estonian kroon',
		'symbol'    => '&#75;&#114;',
	),
	array(
		'code'      => 'EUR',
		'countries' => array( 'European Union', 'Italy', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden' ),
		'name'      => 'Euro',
		'symbol'    => '&#8364;',
	),
	array(
		'code'      => 'FKP',
		'countries' => array( 'Falkland Islands' ),
		'name'      => 'Falkland Islands (Malvinas) Pound',
		'symbol'    => '&#70;&#75;&#163;',
	),
	array(
		'code'      => 'FJD',
		'countries' => array( 'Fiji' ),
		'name'      => 'Fijian dollar',
		'symbol'    => '&#70;&#74;&#36;',
	),
	array(
		'code'      => 'GHC',
		'countries' => array( 'Ghana' ),
		'name'      => 'Ghanaian cedi',
		'symbol'    => '&#71;&#72;&#162;',
	),
	array(
		'code'      => 'GIP',
		'countries' => array( 'Gibraltar' ),
		'name'      => 'Gibraltar pound',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'GTQ',
		'countries' => array( 'Guatemala' ),
		'name'      => 'Guatemalan quetzal',
		'symbol'    => '&#81;',
	),
	array(
		'code'      => 'GGP',
		'countries' => array( 'Guernsey' ),
		'name'      => 'Guernsey pound',
		'symbol'    => '&#81;',
	),
	array(
		'code'      => 'GYD',
		'countries' => array( 'Guyana' ),
		'name'      => 'Guyanese dollar',
		'symbol'    => '&#71;&#89;&#36;',
	),
	array(
		'code'      => 'HNL',
		'countries' => array( 'Honduras' ),
		'name'      => 'Honduran lempira',
		'symbol'    => '&#76;',
	),
	array(
		'code'      => 'HKD',
		'countries' => array( 'Hong Kong' ),
		'name'      => 'Hong Kong dollar',
		'symbol'    => '&#72;&#75;&#36;',
	),
	array(
		'code'      => 'HUF',
		'countries' => array( 'Hungary' ),
		'name'      => 'Hungarian forint',
		'symbol'    => '&#70;&#116;',
	),
	array(
		'code'      => 'ISK',
		'countries' => array( 'Iceland' ),
		'name'      => 'Icelandic króna',
		'symbol'    => '&#237;&#107;&#114;',
	),
	array(
		'code'      => 'INR',
		'countries' => array( 'India' ),
		'name'      => 'Indian rupee',
		'symbol'    => '&#8377;',
	),
	array(
		'code'      => 'IDR',
		'countries' => array( 'Indonesia' ),
		'name'      => 'Indonesian rupiah',
		'symbol'    => '&#82;&#112;',
	),
	array(
		'code'      => 'IRR',
		'countries' => array( 'Iran' ),
		'name'      => 'Iranian rial',
		'symbol'    => '&#65020;',
	),
	array(
		'code'      => 'IMP',
		'countries' => array( 'Isle of Man' ),
		'name'      => 'Manx pound',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'ILS',
		'countries' => array( 'Israel', 'Palestinian territories of the West Bank', 'The Gaza Strip' ),
		'name'      => 'Israeli Shekel',
		'symbol'    => '&#8362;',
	),
	array(
		'code'      => 'JMD',
		'countries' => array( 'Jamaica' ),
		'name'      => 'Jamaican dollar',
		'symbol'    => '&#74;&#36;',
	),
	array(
		'code'      => 'JPY',
		'countries' => array( 'Japan' ),
		'name'      => 'Japanese yen',
		'symbol'    => '&#165;',
	),
	array(
		'code'      => 'JEP',
		'countries' => array( 'Jersey' ),
		'name'      => 'Jersey pound',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'KZT',
		'countries' => array( 'Kazakhstan' ),
		'name'      => 'Kazakhstani tenge',
		'symbol'    => '&#8376;',
	),
	array(
		'code'      => 'KPW',
		'countries' => array( 'North Korea' ),
		'name'      => 'North Korean won',
		'symbol'    => '&#8361;',
	),
	array(
		'code'      => 'KPW',
		'countries' => array( 'South Korea' ),
		'name'      => 'South Korean won',
		'symbol'    => '&#8361;',
	),
	array(
		'code'      => 'KGS',
		'countries' => array( 'Kyrgyz Republic' ),
		'name'      => 'Kyrgyzstani som',
		'symbol'    => '&#1083;&#1074;',
	),
	array(
		'code'      => 'LAK',
		'countries' => array( 'Laos' ),
		'name'      => 'Lao kip',
		'symbol'    => '&#8365;',
	),
	array(
		'code'      => 'LAK',
		'countries' => array( 'Laos' ),
		'name'      => 'Latvian lats',
		'symbol'    => '&#8364;',
	),
	array(
		'code'      => 'LVL',
		'countries' => array( 'Laos' ),
		'name'      => 'Latvian lats',
		'symbol'    => '&#8364;',
	),
	array(
		'code'      => 'LBP',
		'countries' => array( 'Lebanon' ),
		'name'      => 'Lebanese pound',
		'symbol'    => '&#76;&#163;',
	),
	array(
		'code'      => 'LRD',
		'countries' => array( 'Liberia' ),
		'name'      => 'Liberian dollar',
		'symbol'    => '&#76;&#68;&#36;',
	),
	array(
		'code'      => 'LTL',
		'countries' => array( 'Lithuania' ),
		'name'      => 'Lithuanian litas',
		'symbol'    => '&#8364;',
	),
	array(
		'code'      => 'MKD',
		'countries' => array( 'North Macedonia' ),
		'name'      => 'Macedonian denar',
		'symbol'    => '&#1076;&#1077;&#1085;',
	),
	array(
		'code'      => 'MYR',
		'countries' => array( 'Malaysia' ),
		'name'      => 'Malaysian ringgit',
		'symbol'    => '&#82;&#77;',
	),
	array(
		'code'      => 'MUR',
		'countries' => array( 'Mauritius' ),
		'name'      => 'Mauritian rupee',
		'symbol'    => '&#82;&#115;',
	),
	array(
		'code'      => 'MXN',
		'countries' => array( 'Mexico' ),
		'name'      => 'Mexican peso',
		'symbol'    => '&#77;&#101;&#120;&#36;',
	),
	array(
		'code'      => 'MNT',
		'countries' => array( 'Mongolia' ),
		'name'      => 'Mongolian tögrög',
		'symbol'    => '&#8366;',
	),
	array(
		'code'      => 'MZN',
		'countries' => array( 'Mozambique' ),
		'name'      => 'Mozambican metical',
		'symbol'    => '&#77;&#84;',
	),
	array(
		'code'      => 'NAD',
		'countries' => array( 'Namibia' ),
		'name'      => 'Namibian dollar',
		'symbol'    => '&#78;&#36;',
	),
	array(
		'code'      => 'NPR',
		'countries' => array( 'Federal Democratic Republic of Nepal' ),
		'name'      => 'Nepalese rupee',
		'symbol'    => '&#82;&#115;&#46;',
	),
	array(
		'code'      => 'ANG',
		'countries' => array( 'Curaçao', 'Sint Maarten' ),
		'name'      => 'Netherlands Antillean guilder',
		'symbol'    => '&#402;',
	),
	array(
		'code'      => 'NZD',
		'countries' => array( 'New Zealand', 'The Cook Islands', 'Niue', 'The Ross Dependency', 'Tokelau', 'The Pitcairn Islands' ),
		'name'      => 'New Zealand Dollar',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'NIO',
		'countries' => array( 'Nicaragua' ),
		'name'      => 'Nicaraguan córdoba',
		'symbol'    => '&#67;&#36;',
	),
	array(
		'code'      => 'NGN',
		'countries' => array( 'Nigeria' ),
		'name'      => 'Nigerian Naira',
		'symbol'    => '&#8358;',
	),
	array(
		'code'      => 'NOK',
		'countries' => array( 'Norway and its dependent territories' ),
		'name'      => 'Norwegian krone',
		'symbol'    => '&#107;&#114;',
	),
	array(
		'code'      => 'OMR',
		'countries' => array( 'Oman' ),
		'name'      => 'Omani rial',
		'symbol'    => '&#65020;',
	),
	array(
		'code'      => 'PKR',
		'countries' => array( 'Pakistan' ),
		'name'      => 'Pakistani rupee',
		'symbol'    => '&#82;&#115;',
	),
	array(
		'code'      => 'PAB',
		'countries' => array( 'Panama' ),
		'name'      => 'Panamanian balboa',
		'symbol'    => '&#66;&#47;&#46;',
	),
	array(
		'code'      => 'PYG',
		'countries' => array( 'Paraguay' ),
		'name'      => 'Paraguayan Guaraní',
		'symbol'    => '&#8370;',
	),
	array(
		'code'      => 'PEN',
		'countries' => array( 'Peru' ),
		'name'      => 'Sol',
		'symbol'    => '&#83;&#47;&#46;',
	),
	array(
		'code'      => 'PHP',
		'countries' => array( 'Philippines' ),
		'name'      => 'Philippine peso',
		'symbol'    => '&#8369;',
	),
	array(
		'code'      => 'PLN',
		'countries' => array( 'Poland' ),
		'name'      => 'Polish złoty',
		'symbol'    => '&#122;&#322;',
	),
	array(
		'code'      => 'QAR',
		'countries' => array( 'State of Qatar' ),
		'name'      => 'Qatari Riyal',
		'symbol'    => '&#65020;',
	),
	array(
		'code'      => 'RON',
		'countries' => array( 'Romania' ),
		'name'      => 'Romanian leu (Leu românesc)',
		'symbol'    => '&#76;',
	),
	array(
		'code'      => 'RUB',
		'countries' => array( 'Russian Federation', 'Abkhazia and South Ossetia', 'Donetsk and Luhansk' ),
		'name'      => 'Russian ruble',
		'symbol'    => '&#8381;',
	),
	array(
		'code'      => 'SHP',
		'countries' => array( 'Saint Helena', 'Ascension', 'Tristan da Cunha' ),
		'name'      => 'Saint Helena pound',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'SAR',
		'countries' => array( 'Saudi Arabia' ),
		'name'      => 'Saudi riyal',
		'symbol'    => '&#65020;',
	),
	array(
		'code'      => 'RSD',
		'countries' => array( 'Serbia' ),
		'name'      => 'Serbian dinar',
		'symbol'    => '&#100;&#105;&#110;',
	),
	array(
		'code'      => 'SCR',
		'countries' => array( 'Seychelles' ),
		'name'      => 'Seychellois rupee',
		'symbol'    => '&#82;&#115;',
	),
	array(
		'code'      => 'SGD',
		'countries' => array( 'Singapore' ),
		'name'      => 'Singapore dollar',
		'symbol'    => '&#83;&#36;',
	),
	array(
		'code'      => 'SBD',
		'countries' => array( 'Solomon Islands' ),
		'name'      => 'Solomon Islands dollar',
		'symbol'    => '&#83;&#73;&#36;',
	),
	array(
		'code'      => 'SOS',
		'countries' => array( 'Somalia' ),
		'name'      => 'Somali shilling',
		'symbol'    => '&#83;&#104;&#46;&#83;&#111;',
	),
	array(
		'code'      => 'ZAR',
		'countries' => array( 'South Africa' ),
		'name'      => 'South African rand',
		'symbol'    => '&#82;',
	),
	array(
		'code'      => 'LKR',
		'countries' => array( 'Sri Lanka' ),
		'name'      => 'Sri Lankan rupee',
		'symbol'    => '&#82;&#115;',
	),
	array(
		'code'      => 'SEK',
		'countries' => array( 'Sweden' ),
		'name'      => 'Swedish krona',
		'symbol'    => '&#107;&#114;',
	),
	array(
		'code'      => 'CHF',
		'countries' => array( 'Switzerland' ),
		'name'      => 'Swiss franc',
		'symbol'    => '&#67;&#72;&#102;',
	),
	array(
		'code'      => 'SRD',
		'countries' => array( 'Suriname' ),
		'name'      => 'Suriname Dollar',
		'symbol'    => '&#83;&#114;&#36;',
	),
	array(
		'code'      => 'SYP',
		'countries' => array( 'Syria' ),
		'name'      => 'Syrian pound',
		'symbol'    => '&#163;&#83;',
	),
	array(
		'code'      => 'TWD',
		'countries' => array( 'Taiwan' ),
		'name'      => 'New Taiwan dollar',
		'symbol'    => '&#78;&#84;&#36;',
	),
	array(
		'code'      => 'THB',
		'countries' => array( 'Thailand' ),
		'name'      => 'Thai baht',
		'symbol'    => '&#3647;',
	),
	array(
		'code'      => 'TTD',
		'countries' => array( 'Trinidad', 'Tobago' ),
		'name'      => 'Trinidad and Tobago dollar',
		'symbol'    => '&#84;&#84;&#36;',
	),
	array(
		'code'      => 'TRY',
		'countries' => array( 'Turkey', 'Turkish Republic of Northern Cyprus' ),
		'name'      => 'Turkey Lira',
		'symbol'    => '&#8378;',
	),
	array(
		'code'      => 'TVD',
		'countries' => array( 'Tuvalu' ),
		'name'      => 'Tuvaluan dollar',
		'symbol'    => '&#84;&#86;&#36;',
	),
	array(
		'code'      => 'UAH',
		'countries' => array( 'Ukraine' ),
		'name'      => 'Ukrainian hryvnia',
		'symbol'    => '&#8372;',
	),
	array(
		'code'      => 'GBP',
		'countries' => array( 'United Kingdom', 'Jersey', 'Guernsey', 'The Isle of Man', 'Gibraltar', 'South Georgia', 'The South Sandwich Islands', 'The British Antarctic', 'Territory', 'Tristan da Cunha' ),
		'name'      => 'Pound sterling',
		'symbol'    => '&#163;',
	),
	array(
		'code'      => 'UGX',
		'countries' => array( 'Uganda' ),
		'name'      => 'Ugandan shilling',
		'symbol'    => '&#85;&#83;&#104;',
	),
	array(
		'code'      => 'USD',
		'countries' => array( 'United States' ),
		'name'      => 'United States dollar',
		'symbol'    => '&#36;',
	),
	array(
		'code'      => 'UYU',
		'countries' => array( 'Uruguayan' ),
		'name'      => 'Peso Uruguayolar',
		'symbol'    => '&#36;&#85;',
	),
	array(
		'code'      => 'UZS',
		'countries' => array( 'Uzbekistan' ),
		'name'      => 'Uzbekistani soʻm',
		'symbol'    => '&#1083;&#1074;',
	),
	array(
		'code'      => 'VEF',
		'countries' => array( 'Venezuela' ),
		'name'      => 'Venezuelan bolívar',
		'symbol'    => '&#66;&#115;',
	),
	array(
		'code'      => 'VND',
		'countries' => array( 'Vietnam' ),
		'name'      => 'Vietnamese dong (Đồng)',
		'symbol'    => '&#8363;',
	),
	array(
		'code'      => 'YER',
		'countries' => array( 'Yemen' ),
		'name'      => 'Yemeni rial',
		'symbol'    => '&#65020;',
	),
	array(
		'code'      => 'ZWD',
		'countries' => array( 'Zimbabwe' ),
		'name'      => 'Zimbabwean dollar',
		'symbol'    => '&#90;&#36;',
	),
);
